### ISSUE TITLE
image_digester.py fails to run on Python3-default systems

### ISSUE THREAD

**Issue by emempi** [google/containerregistry#157]
On python3-only systems, using image_digester.py fails with erorrs indicating that httplib2 tries to use an API that is Python 2-specific:
```
Traceback (most recent call last):
  File ".../execroot/__main__/bazel-out/host/bin/external/containerregistry/digester.runfiles/containerregistry/tools/image_digester_.py", line 28, in <module>
    from containerregistry.client.v2_2 import docker_image as v2_2_image
  File ".../execroot/__main__/bazel-out/host/bin/external/containerregistry/digester.runfiles/containerregistry/client/__init__.py", line 23, in <module>
    from containerregistry.client import docker_creds_
  File ".../execroot/__main__/bazel-out/host/bin/external/containerregistry/digester.runfiles/containerregistry/client/docker_creds_.py", line 31, in <module>
    import httplib2
  File ".../execroot/__main__/bazel-out/host/bin/external/containerregistry/digester.runfiles/httplib2/__init__.py", line 28, in <module>
    import email.FeedParser
ModuleNotFoundError: No module named 'email.FeedParser'
```

This is likely due to inclusion of a python2-specific httplib2:
https://github.com/google/containerregistry/blob/da03b395ccdc4e149e34fbb540483efce962dc64/def.bzl#L25

**Comment by emempi** [comment]
Actually, looks like this is a duplicate of https://github.com/google/containerregistry/issues/153 . Closing in favor of that one.
