### ISSUE TITLE
Docker Puller tool does not work with Dockerhub images

### ISSUE THREAD

**Issue by infominer75** [google/containerregistry#165]
I am attempting to use the docker puller tool to pull an image from docker hub.

The arguments passed to the tool are as follows:
--name docker.io/libarary/ubuntu:latest --tarball /tmp/ubuntu.tar
I get the following error when I run the command using the arguments:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/home/chaitra/Projects/containers/googlecontainertools/containerregistry/tools/logging_setup.py", line 63, in format
    return super(Formatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 68212: ordinal not in range(128)
Logged from file docker_puller.py, line 135
```

Is this python library compatible with images pulled from docker hub or any custom registry?

**Comment by jonjohnsonjr** [comment]
> The arguments passed to the tool are as follows:
> `--name docker.io/libarary/ubuntu:latest --tarball /tmp/ubuntu.tar`

This looks like a typo: libarary -> library

**Comment by kfuhrmann1** [comment]
Hey @infominer75 . I had the same issue. After trying to work around it for a while, the solution for me was to just use `registry.hub.docker.com` instead of `docker.io`. Hopefully that helps you, too.
