### ISSUE TITLE
Building puller is not reproduceable

### ISSUE THREAD

**Issue by jeb2239** [google/containerregistry#72]
The first time I run
```
bazel build -s --verbose_failures //:pusher.par
```
everything works fine
but the second time I run it there is an error
```
SUBCOMMAND: # //:pusher.par [action 'Building par file //:pusher.par']
(cd /tmp/bazel/output/execroot/containerregistry && \
  exec env - \
  bazel-out/host/bin/external/subpar/compiler/compiler.par --manifest_file bazel-out/k8-fastbuild/bin/pusher.par_SOURCES --outputpar bazel-out/k8-fastbuild/bin/pusher.par --stub_file bazel-out/k8-fastbuild/bin/pusher tools/fast_pusher_.py)
ERROR: /home/barriosj/containerregistry/BUILD.bazel:36:1: Building par file //:pusher.par failed (Exit 1): compiler.par failed: error executing command 
  (cd /tmp/bazel/output/execroot/containerregistry && \
  exec env - \
  bazel-out/host/bin/external/subpar/compiler/compiler.par --manifest_file bazel-out/k8-fastbuild/bin/pusher.par_SOURCES --outputpar bazel-out/k8-fastbuild/bin/pusher.par --stub_file bazel-out/k8-fastbuild/bin/pusher tools/fast_pusher_.py)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/barriosj/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/barriosj/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/__main__.py", line 28, in <module>
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/cli.py", line 114, in main
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/python_archive.py", line 113, in create
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/python_archive.py", line 250, in write_zip_data
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/stored_resource.py", line 51, in store
  File "/home/barriosj/miniconda2/lib/python2.7/zipfile.py", line 1126, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'bazel-bin/pusher.runfiles/__init__.py'
Target //:pusher.par failed to build
INFO: Elapsed time: 0.396s, Critical Path: 0.22s
FAILED: Build did NOT complete successfully
```

**Comment by mattmoor** [comment]
We need to update the version of `google/subpar` we use.  @duggelz made this reproducible relatively recently.

**Comment by mattmoor** [comment]
cc @jonjohnsonjr @dekkagaijin

**Comment by mattmoor** [comment]
Oh, that's probably something else, but may also be fixed by an update to subpar.

**Comment by jonjohnsonjr** [comment]
We need to pick up https://github.com/google/subpar/pull/68 ?

**Comment by jeb2239** [comment]
Wait I am running this on RHEL 7 .

**Comment by jeb2239** [comment]
I can confirm this problem on exists on RHEL 7 and not ubuntu and I assume centos 7 as well.

**Comment by jonjohnsonjr** [comment]
Yeah I don't see this repro on debian, but I'm happy to bump the version of subpar we're using if that will fix this for you.

**Comment by duggelz** [comment]
Can you run `bazel version` and paste in the output?  In the past, I've seen some race conditions where the runfiles symlinks weren't completely built before subpar is invoked, but I thought they were all fixed.

**Comment by jeb2239** [comment]
this also seems to be fine now
