### ISSUE TITLE
ValueError: Single '}' encountered in format string

### ISSUE THREAD

**Issue by azr** [google/containerregistry#73]
Howdy,

```
INFO: Running command line: bazel-bin/cmd/translation/push_image

Traceback (most recent call last):
  File "/tmp/build/cache/execroot/__main__/bazel-out/k8-fastbuild/bin/cmd/translation/push_image.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 141, in <module>
    main()
  File "/tmp/build/cache/execroot/__main__/bazel-out/k8-fastbuild/bin/cmd/translation/push_image.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 96, in main
    name = Tag(args.name, args.stamp_info_file)
  File "/tmp/build/cache/execroot/__main__/bazel-out/k8-fastbuild/bin/cmd/translation/push_image.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 78, in Tag
    formatted_name = name.format(**format_args)
ValueError: Single '}' encountered in format string
[31m[1mERROR: [0mNon-zero return code '1' from command: Process exited with status 1
```
Googled my way to nowhere and thought I'd ask here, may be someone had or will get this. :)

I'll keep on trying and share any fix if I do find some.

Thanks for any help !

**Comment by azr** [comment]
Ah, reading the code from the said file L78:
https://github.com/google/containerregistry/blob/bbdf8c3b6d064a8ae0c22426c248c8e4e4bf4b56/tools/fast_pusher_.py#L76-L79

My tag had a typo: `ft-redirect-map}-`. I should have started there...
Welp, I know a fix for that :D.
