### ISSUE TITLE
Name option parsing

### ISSUE THREAD

**Issue by jeb2239** [google/containerregistry#84]
`bazel-bin/external/containerregistry/puller.par --name index.docker.io/openjdk --directory .`

I don't really know any other interpretation of the name option.

```
Running command line: bazel-bin/external/containerregistry/puller.par --name index.docker.io/openjdk --directory .
Traceback (most recent call last):
  File "/home/barriosj/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/barriosj/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/barriosj/705e5906a0d5fed56361de3c80f1e60f/execroot/containerregistry/bazel-out/k8-fastbuild/bin/external/containerregistry/puller.par/__main__.py", line 133, in <module>
  File "/tmp/barriosj/705e5906a0d5fed56361de3c80f1e60f/execroot/containerregistry/bazel-out/k8-fastbuild/bin/external/containerregistry/puller.par/__main__.py", line 80, in main
  File "/tmp/barriosj/705e5906a0d5fed56361de3c80f1e60f/execroot/containerregistry/bazel-out/k8-fastbuild/bin/external/containerregistry/puller.par/containerregistry/client/docker_name_.py", line 211, in __init__
  File "/tmp/barriosj/705e5906a0d5fed56361de3c80f1e60f/execroot/containerregistry/bazel-out/k8-fastbuild/bin/external/containerregistry/puller.par/containerregistry/client/docker_name_.py", line 80, in _check_tag
  File "/tmp/barriosj/705e5906a0d5fed56361de3c80f1e60f/execroot/containerregistry/bazel-out/k8-fastbuild/bin/external/containerregistry/puller.par/containerregistry/client/docker_name_.py", line 64, in _check_element
containerregistry.client.docker_name_.BadNameException: Invalid tag: , must be at least 1 characters
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by jonjohnsonjr** [comment]
Does `index.docker.io/library/openjdk` work? The "official" images are under the "library" namespace on DockerHub.

**Comment by pcj** [comment]
Or maybe `index.docker.io/library/openjdk:latest`.  Try adding an image tag.

**Comment by jeb2239** [comment]
Yeah thanks for the help!
